### ISSUE TITLE
Support for TinkerPop3

### ISSUE THREAD

**Issue by SecSan** [dkuppitz/rexpro-client#8]
Hi Daniel,

first of all: Thanks for your great work on rexpro-client! It makes it really easy to connect to Titan from C#.
But do you by any chance intend to adjust rexpro-client to support Tinkerpop3's Gremlin Server which replaces Rexster? Since Gremlin Server uses web sockets instead of a binary protocol like RexPro, a completely new project might be necessary for this, but I'm sure that the demand for a C# Gremlin driver will grow with the release of TP3 GA.

**Comment by dkuppitz** [comment]
I will no longer maintain the rexpro-client project, since I got rid of my .NET development environment a while back. However, I bet it won't take long until the first .NET client library appears after TP3 GA.
